package com.medichain.modules.trazabilidad;

/**
 * Enumeración TipoEvento en MediChain.
 * Cataloga todos los hechos de negocio que quedan asentados en la
 * cadena de eventos de trazabilidad (EventoTrazabilidad), a lo largo de
 * los 17 módulos del dominio.
 */
public enum TipoEvento {
    ALTA_INSPECTOR,
    BAJA_INSPECTOR,
    REACTIVACION_INSPECTOR,
    SOLICITUD_HABILITACION,
    SOLICITUD_TOMADA,
    SOLICITUD_ASIGNADA,
    HABILITACION_APROBADA,
    HABILITACION_RECHAZADA,
    EMPRESA_SUSPENDIDA,
    EMPRESA_REHABILITADA,
    CIRCUITO_PROPUESTO,
    CIRCUITO_ACEPTADO,
    CIRCUITO_RECHAZADO,
    CIRCUITO_TOMADO,
    CIRCUITO_ASIGNADO,
    CIRCUITO_APROBADO,
    CIRCUITO_SUSPENDIDO,
    CIRCUITO_REHABILITADO,
    MEDICAMENTO_REGISTRADO,
    LOTE_REGISTRADO,
    LOTE_LIBERADO,
    INTENTO_SERIE_INVALIDA,
    BULTO_ARMADO,
    BULTO_DESARMADO,
    VIAJE_CREADO,
    VIAJE_SALIDA,
    VIAJE_CANCELADO,
    RUPTURA_FRIO,
    VIAJE_FINALIZADO,
    ROBO_EXTRAVIO,
    BULTO_RECIBIDO,
    BULTO_RECHAZADO,
    BULTO_INEXISTENTE,
    BULTO_DUPLICADO,
    CUARENTENA,
    CUARENTENA_TOMADA,
    CUARENTENA_LEVANTADA,
    RECALL,
    DISPENSACION,
    ANULACION_DISPENSA,
    DEVOLUCION,
    INTENTO_DUPLICADO,
    SERIE_INEXISTENTE,
    SERIE_ROBADA,
    REPORTE_CIUDADANO,
    REPORTE_TOMADO,
    REPORTE_CERRADO
}
